### ISSUE TITLE
Installation help

### ISSUE THREAD

**Issue by wildlifechorus** [PeterDaveHello/Drone-GitHub-status-report-bot#1]
Hey man,

You think you could add some installation instructions please?

Best regards

**Comment by PeterDaveHello** [comment]
Sure thing, before it's done, please take a look at the example here which I think it might help!

https://github.com/cdnjs/cdnjs/blob/master/.drone.yml#L5-L9
```yaml
  bot-review:
    image: peterdavehello/drone-github-status-report-bot:latest
    when:
      event: pull_request
      status: [ success, failure ]
```

Thanks!
